const data={
    products: [
        {
          _id: '1',
          name: 'Yoke Rayon Top',
          category: 'Top',
          image: '/images/p1.jpg',
          price: 120,
          countInStock: 10,
          brand: 'Yoke',
          rating: 4.5,
          numReviews: 10,
          description: 'high quality Ladies product',
        },
        {
            _id: '2',
            name: 'Saakaa woman Top',
            category: 'Top',
            image: '/images/p2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Saakaa',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality Ladies product',
          },
          {
            _id: '3',
            name: 'Jazzy Ben Top',
            category: 'Top',
            image: '/images/p3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Jazzy',
            rating: 4.5,
            numReviews: 18,
            description: 'high quality Ladies product',
          },
          {
            _id: '4',
            name: 'Zaphire Multicolored Top',
            category: 'Top',
            image: '/images/p4.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Zaphire',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality Ladies product',
          },
          {
            _id: '5',
            name: 'Fabrange regular Top',
            category: 'Top',
            image: '/images/p5.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Fabrange',
            rating: 4.5,
            numReviews: 25,
            description: 'high quality Ladies product',
          },
          {
            _id: '6',
            name: 'Tunics Ladies Top',
            category: 'Top',
            image: '/images/p6.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Tunics',
            rating: 4.5,
            numReviews: 35,
            description: 'high quality Ladies product',
          },

    ]
};
export default data;   

    
